# ===========================
# CONFIGURACIÓN DINÁMICA (LOCAL / NUBE)
# ===========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/contabilidad_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:supervisor}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=${PORT:8080}

# Permitir acceso público a la documentación en producción
springdoc.swagger-ui.operationsSorter=alpha
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Uso del protocolo HTTPS seguro y proxy de Render
server.forward-headers-strategy=framework

# Spring Boot a mantener el servidor web Tomcat activo
spring.main.web-application-type=servlet

spring.jpa.open-in-view=false
springdoc.packages-to-scan=com.contabilidad.api
